### ISSUE TITLE
Project does not build after clone

### ISSUE THREAD

**Issue by kbaes2804** [hpehl/quarkus-grpc-extension#3]
Hi, I have cloned this project and `mvn package` in the root fails. I presume this is because all the versions are invalid. Am I missing something or am I supposed to manually sort out the versions in my local repo?

Thanks in advance!

**Comment by hpehl** [comment]
Should be fixed now with last commit. Could you please verify?

**Comment by kbaes2804** [comment]
The install works, for my use case I had to set `grpc.version` to 1.22.1 from 1.22.0. My proto project uses that version of GRPC so there was a conflict there.

Building a native image does not work however since Netty is a transitive dependency of GRPC. I'm going to use [this article](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) to try and make it work in my project. I don't know if it would be a good idea/feasible to generalize the GraalVM configuration to make Netty work in this extension.

Closing since the original issue was addressed.
